# compose.yaml
services:
  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=500
    ports:
      - "8000:8000"
    volumes:
      - .:/app